# Embedding Model (Prototype)

In [336]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Data Loading

In [337]:
# Load the data
train_x_df = pd.read_csv('../data/X_train.csv')
train_y_df = pd.read_csv('../data/Y_train.csv')

test_x_df = pd.read_csv('../data/X_test.csv')

C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\460957917.py:2: DtypeWarning: Columns (21,22,23,24,69,70,71,72,93,94,95,96,97,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120) have mixed types. Specify dtype option on import or set low_memory=False.
  train_x_df = pd.read_csv('../data/X_train.csv')
C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\460957917.py:5: DtypeWarning: Columns (20,21,22,23,24,68,69,70,71,72,92,93,94,95,96,97,106,107,108,109,110,111,112,113,114,115,116,117,118) have mixed types. Specify dtype option on import or set low_memory=False.
  test_x_df = pd.read_csv('../data/X_test.csv')

### Get String-based features

In [338]:
item_cols = [f'item{i}' for i in range(1, 25)]
make_cols = [f'make{i}' for i in range(1, 25)]
goods_cols = [f'goods_code{i}' for i in range(1, 25)]

cat_cols = item_cols + make_cols + goods_cols

print(cat_cols);

train_x_df[cat_cols].head()

['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'item7', 'item8', 'item9', 'item10', 'item11', 'item12', 'item13', 'item14', 'item15', 'item16', 'item17', 'item18', 'item19', 'item20', 'item21', 'item22', 'item23', 'item24', 'make1', 'make2', 'make3', 'make4', 'make5', 'make6', 'make7', 'make8', 'make9', 'make10', 'make11', 'make12', 'make13', 'make14', 'make15', 'make16', 'make17', 'make18', 'make19', 'make20', 'make21', 'make22', 'make23', 'make24', 'goods_code1', 'goods_code2', 'goods_code3', 'goods_code4', 'goods_code5', 'goods_code6', 'goods_code7', 'goods_code8', 'goods_code9', 'goods_code10', 'goods_code11', 'goods_code12', 'goods_code13', 'goods_code14', 'goods_code15', 'goods_code16', 'goods_code17', 'goods_code18', 'goods_code19', 'goods_code20', 'goods_code21', 'goods_code22', 'goods_code23', 'goods_code24']

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,COMPUTERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,COMPUTERS,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Fill NaN values with a flag string

In [339]:
train_x_df[cat_cols] = train_x_df[cat_cols].fillna("NONE")
test_x_df[cat_cols] = test_x_df[cat_cols].fillna("NONE")

train_x_df[cat_cols].head()

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,COMPUTERS,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
1,COMPUTER PERIPHERALS ACCESSORIES,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
2,TELEVISIONS HOME CINEMA,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
3,COMPUTERS,COMPUTER PERIPHERALS ACCESSORIES,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
4,TELEVISIONS HOME CINEMA,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE

### Numerically encode all categorical values and clean the numeric values

In [340]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in cat_cols:

    le = LabelEncoder()

    combined_data = pd.concat([
        train_x_df[col],
        test_x_df[col]
    ]).astype(str)

    le.fit(combined_data)

    train_x_df[col] = le.transform(train_x_df[col].astype(str))
    test_x_df[col] = le.transform(test_x_df[col].astype(str))

    encoders[col] = le

train_x_df[cat_cols].head()

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,38,95,92,87,77,70,70,66,59,60,...,216,192,162,137,122,102,86,72,58,54
1,36,95,92,87,77,70,70,66,59,60,...,216,192,162,137,122,102,86,72,58,54
2,122,95,92,87,77,70,70,66,59,60,...,216,192,162,137,122,102,86,72,58,54
3,38,35,92,87,77,70,70,66,59,60,...,216,192,162,137,122,102,86,72,58,54
4,122,95,92,87,77,70,70,66,59,60,...,216,192,162,137,122,102,86,72,58,54

In [ ]:
# Get the number of unique categories for each categorical column
embedding_sizes = {}

for col in cat_cols:

    embedding_size = train_x_df[col].max() + 1
    
    embedding_sizes[col] = embedding_size

print(embedding_sizes)

{'item1': np.int64(136), 'item2': np.int64(139), 'item3': np.int64(135), 'item4': np.int64(128), 'item5': np.int64(112), 'item6': np.int64(105), 'item7': np.int64(101), 'item8': np.int64(96), 'item9': np.int64(86), 'item10': np.int64(80), 'item11': np.int64(74), 'item12': np.int64(68), 'item13': np.int64(63), 'item14': np.int64(63), 'item15': np.int64(62), 'item16': np.int64(50), 'item17': np.int64(53), 'item18': np.int64(47), 'item19': np.int64(43), 'item20': np.int64(38), 'item21': np.int64(34), 'item22': np.int64(29), 'item23': np.int64(25), 'item24': np.int64(27), 'make1': np.int64(475), 'make2': np.int64(459), 'make3': np.int64(407), 'make4': np.int64(338), 'make5': np.int64(302), 'make6': np.int64(231), 'make7': np.int64(213), 'make8': np.int64(179), 'make9': np.int64(159), 'make10': np.int64(142), 'make11': np.int64(124), 'make12': np.int64(115), 'make13': np.int64(95), 'make14': np.int64(91), 'make15': np.int64(78), 'make16': np.int64(70), 'make17': np.int64(55), 'make18': np.int64(50), 'make19': np.int64(52), 'make20': np.int64(42), 'make21': np.int64(35), 'make22': np.int64(28), 'make23': np.int64(31), 'make24': np.int64(24), 'goods_code1': np.int64(6748), 'goods_code2': np.int64(5500), 'goods_code3': np.int64(3832), 'goods_code4': np.int64(2537), 'goods_code5': np.int64(1774), 'goods_code6': np.int64(1241), 'goods_code7': np.int64(987), 'goods_code8': np.int64(770), 'goods_code9': np.int64(623), 'goods_code10': np.int64(513), 'goods_code11': np.int64(432), 'goods_code12': np.int64(353), 'goods_code13': np.int64(295), 'goods_code14': np.int64(253), 'goods_code15': np.int64(217), 'goods_code16': np.int64(193), 'goods_code17': np.int64(163), 'goods_code18': np.int64(138), 'goods_code19': np.int64(123), 'goods_code20': np.int64(103), 'goods_code21': np.int64(87), 'goods_code22': np.int64(73), 'goods_code23': np.int64(59), 'goods_code24': np.int64(55)}

In [342]:
# Identify numeric columns
numeric_cols = [
    col for col in train_x_df.columns
    if col not in cat_cols + ['ID'] + ['Nb_of_items'] + ['model' + str(i) for i in range(1, 25)]
]

print(numeric_cols)

train_x_df[numeric_cols].head()

['cash_price1', 'cash_price2', 'cash_price3', 'cash_price4', 'cash_price5', 'cash_price6', 'cash_price7', 'cash_price8', 'cash_price9', 'cash_price10', 'cash_price11', 'cash_price12', 'cash_price13', 'cash_price14', 'cash_price15', 'cash_price16', 'cash_price17', 'cash_price18', 'cash_price19', 'cash_price20', 'cash_price21', 'cash_price22', 'cash_price23', 'cash_price24', 'Nbr_of_prod_purchas1', 'Nbr_of_prod_purchas2', 'Nbr_of_prod_purchas3', 'Nbr_of_prod_purchas4', 'Nbr_of_prod_purchas5', 'Nbr_of_prod_purchas6', 'Nbr_of_prod_purchas7', 'Nbr_of_prod_purchas8', 'Nbr_of_prod_purchas9', 'Nbr_of_prod_purchas10', 'Nbr_of_prod_purchas11', 'Nbr_of_prod_purchas12', 'Nbr_of_prod_purchas13', 'Nbr_of_prod_purchas14', 'Nbr_of_prod_purchas15', 'Nbr_of_prod_purchas16', 'Nbr_of_prod_purchas17', 'Nbr_of_prod_purchas18', 'Nbr_of_prod_purchas19', 'Nbr_of_prod_purchas20', 'Nbr_of_prod_purchas21', 'Nbr_of_prod_purchas22', 'Nbr_of_prod_purchas23', 'Nbr_of_prod_purchas24']

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas15,Nbr_of_prod_purchas16,Nbr_of_prod_purchas17,Nbr_of_prod_purchas18,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24
0,889.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,409.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1399.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,689.0,119.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1199.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [343]:
# Clean numberic columns by converting to numeric and filling NaNs with 0
train_x_df[numeric_cols] = train_x_df[numeric_cols].apply(pd.to_numeric, errors="coerce").fillna(0)
test_x_df[numeric_cols] = test_x_df[numeric_cols].apply(pd.to_numeric, errors="coerce").fillna(0)

train_x_df[numeric_cols].head()

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas15,Nbr_of_prod_purchas16,Nbr_of_prod_purchas17,Nbr_of_prod_purchas18,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24
0,889.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,409.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1399.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,689.0,119.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1199.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Add aggregated numeric values (like average item price)

In [344]:
qty_cols = [f'Nbr_of_prod_purchas{i}' for i in range(1, 25)]

price_cols = [f'cash_price{i}' for i in range(1, 25)]

train_x_df['total_item_count'] = train_x_df[qty_cols].sum(axis=1)
train_x_df['total_price'] = train_x_df[price_cols].sum(axis=1)
train_x_df['max_price'] = train_x_df[price_cols].max(axis=1)
train_x_df['mean_price'] = train_x_df[price_cols].sum(axis=1) / train_x_df['total_item_count']

test_x_df['total_item_count'] = test_x_df[qty_cols].sum(axis=1)
test_x_df['total_price'] = test_x_df[price_cols].sum(axis=1)
test_x_df['max_price'] = test_x_df[price_cols].max(axis=1)
test_x_df['mean_price'] = test_x_df[price_cols].sum(axis=1) / test_x_df['total_item_count']

# Refresh numeric cols list to include new features
numeric_cols = [
    col for col in train_x_df.columns
    if col not in cat_cols + ['ID'] + ['Nb_of_items'] + ['model' + str(i) for i in range(1, 25)]
]

print(numeric_cols)

train_x_df[numeric_cols].head()

['cash_price1', 'cash_price2', 'cash_price3', 'cash_price4', 'cash_price5', 'cash_price6', 'cash_price7', 'cash_price8', 'cash_price9', 'cash_price10', 'cash_price11', 'cash_price12', 'cash_price13', 'cash_price14', 'cash_price15', 'cash_price16', 'cash_price17', 'cash_price18', 'cash_price19', 'cash_price20', 'cash_price21', 'cash_price22', 'cash_price23', 'cash_price24', 'Nbr_of_prod_purchas1', 'Nbr_of_prod_purchas2', 'Nbr_of_prod_purchas3', 'Nbr_of_prod_purchas4', 'Nbr_of_prod_purchas5', 'Nbr_of_prod_purchas6', 'Nbr_of_prod_purchas7', 'Nbr_of_prod_purchas8', 'Nbr_of_prod_purchas9', 'Nbr_of_prod_purchas10', 'Nbr_of_prod_purchas11', 'Nbr_of_prod_purchas12', 'Nbr_of_prod_purchas13', 'Nbr_of_prod_purchas14', 'Nbr_of_prod_purchas15', 'Nbr_of_prod_purchas16', 'Nbr_of_prod_purchas17', 'Nbr_of_prod_purchas18', 'Nbr_of_prod_purchas19', 'Nbr_of_prod_purchas20', 'Nbr_of_prod_purchas21', 'Nbr_of_prod_purchas22', 'Nbr_of_prod_purchas23', 'Nbr_of_prod_purchas24', 'total_item_count', 'total_price', 'max_price', 'mean_price']

C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\3222992749.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['total_item_count'] = train_x_df[qty_cols].sum(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\3222992749.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['total_price'] = train_x_df[price_cols].sum(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\3222992749.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['max_price'] = train_x_df[price_cols].max(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\3222992749.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['mean_price'] = train_x_df[price_cols].sum(axis=1) / train_x_df['total_item_count']
C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\3222992749.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['total_item_count'] = test_x_df[qty_cols].sum(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\3222992749.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['total_price'] = test_x_df[price_cols].sum(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\3222992749.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['max_price'] = test_x_df[price_cols].max(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_13120\3222992749.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['mean_price'] = test_x_df[price_cols].sum(axis=1) / test_x_df['total_item_count']

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24,total_item_count,total_price,max_price,mean_price
0,889.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,889.0,889.0,889.0
1,409.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,409.0,409.0,409.0
2,1399.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1399.0,1399.0,1399.0
3,689.0,119.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,808.0,689.0,404.0
4,1199.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1199.0,1199.0,1199.0

### Scaling / Normalisation

In [345]:
for col in numeric_cols:

    train_x_df[col] = np.log1p(train_x_df[col])
    test_x_df[col] = np.log1p(test_x_df[col])

train_x_df[numeric_cols].head()

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24,total_item_count,total_price,max_price,mean_price
0,6.791221,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,6.791221,6.791221,6.791221
1,6.016157,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,6.016157,6.016157,6.016157
2,7.244228,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,7.244228,7.244228,7.244228
3,6.536692,4.787492,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.098612,6.695799,6.536692,6.003887
4,7.090077,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,7.090077,7.090077,7.090077

### Convert to Tensors

In [346]:
import torch

X_cat = torch.tensor(
    train_x_df[cat_cols].values,
    dtype=torch.long
)

X_cat_test = torch.tensor(
    test_x_df[cat_cols].values,
    dtype=torch.long
)

X_num = torch.tensor(
    train_x_df[numeric_cols].values,
    dtype=torch.float32
)

X_num_test = torch.tensor(
    test_x_df[numeric_cols].values,
    dtype=torch.float32
)

y = train_y_df["fraud_flag"].values

y_tensor = torch.tensor(
    y,
    dtype=torch.float32
)

print(X_cat.shape)
print(X_num.shape)
print(y_tensor.shape)

print(X_cat[:1])
print(X_num[:1])

torch.Size([92790, 72])
torch.Size([92790, 52])
torch.Size([92790])
tensor([[  38,   95,   92,   87,   77,   70,   70,   66,   59,   60,   51,   45,
           44,   46,   43,   36,   42,   35,   32,   24,   25,   21,   17,   21,
           20,  287,  256,  209,  187,  136,  138,  114,   96,   88,   77,   63,
           59,   56,   51,   45,   30,   32,   29,   23,   16,   15,   19,   15,
         4958, 5498, 3830, 2535, 1772, 1239,  985,  768,  621,  511,  431,  352,
          294,  252,  216,  192,  162,  137,  122,  102,   86,   72,   58,   54]])
tensor([[6.7912, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6931, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.6931, 6.7912, 6.7912, 6.7912]])

### Train / Validation Split

In [347]:
from sklearn.model_selection import train_test_split

X_cat_train, X_cat_val, X_num_train, X_num_val, y_train, y_val = train_test_split(
    X_cat, X_num, y_tensor, test_size=0.15, random_state=42
)

print(type(y_val))
print(np.shape(y_val))
print(y_val[:95])

<class 'torch.Tensor'>
torch.Size([13919])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1.])

### Create Dataset class

In [348]:
from torch.utils.data import Dataset

class FraudDataset(Dataset):

    def __init__(self, X_cat, X_num, y=None):

        self.X_cat = X_cat
        self.X_num = X_num
        self.y = y

    def __len__(self):
        return len(self.X_cat)

    def __getitem__(self, idx):

        if self.y is not None:
            return (
                self.X_cat[idx],
                self.X_num[idx],
                self.y[idx]
            )

        return (
            self.X_cat[idx],
            self.X_num[idx]
        )

### Create the Datasets and Dataloaders

In [349]:
train_dataset = FraudDataset(
    X_cat_train,
    X_num_train,
    y_train
)

val_dataset = FraudDataset(
    X_cat_val,
    X_num_val,
    y_val
)

test_dataset = FraudDataset(
    X_cat_test,
    X_num_test
)

In [350]:
from torch.utils.data import DataLoader

batch_size = 256

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)

### Define Embedding Layers and main Neural Network

In [351]:
import torch.nn as nn

class FraudModel(nn.Module):

    def __init__(self, embedding_sizes, n_numeric):

        super().__init__()

        self.embeddings = nn.ModuleList()

        total_embedding_dim = 0

        # Create one embedding layer per categorical column
        for col, size in embedding_sizes.items():

            emb_dim = min(50, (size // 2) + 1)

            emb = nn.Embedding(size + 1, emb_dim)

            self.embeddings.append(emb)

            total_embedding_dim += emb_dim

        # Main model
        self.fc = nn.Sequential(

            nn.Linear(
                total_embedding_dim + n_numeric,
                32
            ),

            nn.ReLU(),

            nn.Dropout(0.25),

            nn.Linear(32, 16),

            nn.ReLU(),
            
            #nn.Dropout(0.2),

            nn.Linear(16, 1)
        )

    def forward(self, x_cat, x_num):

        embeddings = []

        # Process each categorical column
        for i, emb_layer in enumerate(self.embeddings):

            emb = emb_layer(x_cat[:, i])

            embeddings.append(emb)

        # Concatenate all embeddings
        x = torch.cat(embeddings, dim=1)

        # Add numeric features
        x = torch.cat([x, x_num], dim=1)

        # Feed into neural network
        x = self.fc(x)

        return x.squeeze()

### Instantiate Model

In [352]:
model = FraudModel(
    embedding_sizes=embedding_sizes,
    n_numeric=len(numeric_cols)
)

### Prepare for Training and Validation

In [353]:
criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [354]:
def evaluate(model, X_cat_val, X_num_val, y_val):

    model.eval()

    with torch.no_grad():

        logits = model(X_cat_val, X_num_val)

        probs = torch.sigmoid(logits).cpu().numpy()

        score = average_precision_score(y_val, probs)

    return score

In [355]:
print(np.unique(y)[:200])
print(y.shape)

[0 1]
(92790,)

### Train and Validate

In [356]:
from sklearn.metrics import average_precision_score

best_score = 0

for epoch in range(50):

    model.train()

    train_losses = []

    for X_cat_batch, X_num_batch, y_batch in train_loader:

        optimizer.zero_grad()

        logits = model(X_cat_batch, X_num_batch)

        loss = criterion(logits, y_batch)

        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            1.0
        )

        optimizer.step()

        train_losses.append(loss.item())

    # VALIDATION
    model.eval()

    all_probs = []
    all_targets = []

    with torch.no_grad():

        for X_cat_batch, X_num_batch, y_batch in val_loader:

            logits = model(X_cat_batch, X_num_batch)

            probs = torch.sigmoid(logits)

            all_probs.extend(
                probs.cpu().numpy()
            )

            all_targets.extend(
                y_batch.cpu().numpy()
            )

    pr_auc = average_precision_score(
        all_targets,
        all_probs
    )

    if pr_auc > best_score:
        best_score = pr_auc
        torch.save(
            model.state_dict(),
            "best_model.pt"
        )
        print(f"New best model saved with PR-AUC: {pr_auc:.4f}")

    print(
        f"Epoch {epoch} | "
        f"Loss {np.mean(train_losses):.4f} | "
        f"PR-AUC {pr_auc:.4f}"
    )

model.load_state_dict(
    torch.load("best_model.pt")
)

New best model saved with PR-AUC: 0.0339
Epoch 0 | Loss 0.0874 | PR-AUC 0.0339
New best model saved with PR-AUC: 0.0701
Epoch 1 | Loss 0.0697 | PR-AUC 0.0701
New best model saved with PR-AUC: 0.0814
Epoch 2 | Loss 0.0668 | PR-AUC 0.0814
New best model saved with PR-AUC: 0.0945
Epoch 3 | Loss 0.0637 | PR-AUC 0.0945
New best model saved with PR-AUC: 0.1009
Epoch 4 | Loss 0.0621 | PR-AUC 0.1009
New best model saved with PR-AUC: 0.1032
Epoch 5 | Loss 0.0603 | PR-AUC 0.1032
Epoch 6 | Loss 0.0597 | PR-AUC 0.1007
New best model saved with PR-AUC: 0.1085
Epoch 7 | Loss 0.0585 | PR-AUC 0.1085
New best model saved with PR-AUC: 0.1177
Epoch 8 | Loss 0.0581 | PR-AUC 0.1177
Epoch 9 | Loss 0.0573 | PR-AUC 0.1173
Epoch 10 | Loss 0.0566 | PR-AUC 0.1096
Epoch 11 | Loss 0.0568 | PR-AUC 0.1159
Epoch 12 | Loss 0.0564 | PR-AUC 0.1098
Epoch 13 | Loss 0.0558 | PR-AUC 0.1171
New best model saved with PR-AUC: 0.1264
Epoch 14 | Loss 0.0557 | PR-AUC 0.1264
Epoch 15 | Loss 0.0555 | PR-AUC 0.1223
Epoch 16 | Loss 0.0553 | PR-AUC 0.1248
Epoch 17 | Loss 0.0548 | PR-AUC 0.1220
New best model saved with PR-AUC: 0.1269
Epoch 18 | Loss 0.0545 | PR-AUC 0.1269
New best model saved with PR-AUC: 0.1297
Epoch 19 | Loss 0.0550 | PR-AUC 0.1297
New best model saved with PR-AUC: 0.1322
Epoch 20 | Loss 0.0543 | PR-AUC 0.1322
Epoch 21 | Loss 0.0546 | PR-AUC 0.1291
Epoch 22 | Loss 0.0541 | PR-AUC 0.1313
Epoch 23 | Loss 0.0537 | PR-AUC 0.1236
New best model saved with PR-AUC: 0.1354
Epoch 24 | Loss 0.0537 | PR-AUC 0.1354
Epoch 25 | Loss 0.0538 | PR-AUC 0.1291
Epoch 26 | Loss 0.0534 | PR-AUC 0.1311
Epoch 27 | Loss 0.0532 | PR-AUC 0.1318
Epoch 28 | Loss 0.0532 | PR-AUC 0.1255
Epoch 29 | Loss 0.0533 | PR-AUC 0.1272
Epoch 30 | Loss 0.0532 | PR-AUC 0.1339
Epoch 31 | Loss 0.0531 | PR-AUC 0.1259
Epoch 32 | Loss 0.0532 | PR-AUC 0.1286
Epoch 33 | Loss 0.0528 | PR-AUC 0.1309
Epoch 34 | Loss 0.0530 | PR-AUC 0.1256
New best model saved with PR-AUC: 0.1383
Epoch 35 | Loss 0.0528 | PR-AUC 0.1383
Epoch 36 | Loss 0.0527 | PR-AUC 0.1347
Epoch 37 | Loss 0.0524 | PR-AUC 0.1265
Epoch 38 | Loss 0.0525 | PR-AUC 0.1314
Epoch 39 | Loss 0.0522 | PR-AUC 0.1340
Epoch 40 | Loss 0.0527 | PR-AUC 0.1348
Epoch 41 | Loss 0.0527 | PR-AUC 0.1332
Epoch 42 | Loss 0.0527 | PR-AUC 0.1350
Epoch 43 | Loss 0.0523 | PR-AUC 0.1345
Epoch 44 | Loss 0.0524 | PR-AUC 0.1341
Epoch 45 | Loss 0.0527 | PR-AUC 0.1369
New best model saved with PR-AUC: 0.1397
Epoch 46 | Loss 0.0521 | PR-AUC 0.1397
Epoch 47 | Loss 0.0523 | PR-AUC 0.1314
Epoch 48 | Loss 0.0520 | PR-AUC 0.1338
Epoch 49 | Loss 0.0518 | PR-AUC 0.1294

### Test Set Predicitons

In [357]:
model.eval()

test_probs = []

with torch.no_grad():

    for X_cat_batch, X_num_batch in test_loader:

        logits = model(X_cat_batch, X_num_batch)

        probs = torch.sigmoid(logits)

        test_probs.extend(
            probs.cpu().numpy().flatten()
        )

### Write submission CSV for challenge

In [ ]:
submission = pd.DataFrame({
    "index": range(len(test_x_df)),
    "ID": test_x_df["ID"],
    "fraud_flag": test_probs
})

submission.to_csv("submission.csv", index=False)

print(submission.head())
print("\nsubmission.csv saved!")

   index     ID  fraud_flag
0      0  64707    0.000004
1      1  63919    0.000051
2      2  15664    0.021698
3      3   6626    0.036696
4      4  26766    0.090533

submission.csv saved!