# Embedding Model (Prototype)

In [106]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Data Loading

In [107]:
# Load the data
train_x_df = pd.read_csv('../../data/X_train.csv')
train_y_df = pd.read_csv('../../data/Y_train.csv')

test_x_df = pd.read_csv('../../data/X_test.csv')

C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3151947916.py:2: DtypeWarning: Columns (21,22,23,24,69,70,71,72,93,94,95,96,97,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120) have mixed types. Specify dtype option on import or set low_memory=False.
  train_x_df = pd.read_csv('../../data/X_train.csv')
C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3151947916.py:5: DtypeWarning: Columns (20,21,22,23,24,68,69,70,71,72,92,93,94,95,96,97,106,107,108,109,110,111,112,113,114,115,116,117,118) have mixed types. Specify dtype option on import or set low_memory=False.
  test_x_df = pd.read_csv('../../data/X_test.csv')

### Get Categorical features

In [108]:
item_cols = [f'item{i}' for i in range(1, 25)]
make_cols = [f'make{i}' for i in range(1, 25)]
goods_cols = [f'goods_code{i}' for i in range(1, 25)]

cat_cols = item_cols + make_cols + goods_cols

print(cat_cols);

train_x_df[cat_cols].head()

['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'item7', 'item8', 'item9', 'item10', 'item11', 'item12', 'item13', 'item14', 'item15', 'item16', 'item17', 'item18', 'item19', 'item20', 'item21', 'item22', 'item23', 'item24', 'make1', 'make2', 'make3', 'make4', 'make5', 'make6', 'make7', 'make8', 'make9', 'make10', 'make11', 'make12', 'make13', 'make14', 'make15', 'make16', 'make17', 'make18', 'make19', 'make20', 'make21', 'make22', 'make23', 'make24', 'goods_code1', 'goods_code2', 'goods_code3', 'goods_code4', 'goods_code5', 'goods_code6', 'goods_code7', 'goods_code8', 'goods_code9', 'goods_code10', 'goods_code11', 'goods_code12', 'goods_code13', 'goods_code14', 'goods_code15', 'goods_code16', 'goods_code17', 'goods_code18', 'goods_code19', 'goods_code20', 'goods_code21', 'goods_code22', 'goods_code23', 'goods_code24']

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,COMPUTERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,COMPUTERS,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Fill NaN values with a flag string

In [109]:
train_x_df[cat_cols] = train_x_df[cat_cols].fillna("NONE")
test_x_df[cat_cols] = test_x_df[cat_cols].fillna("NONE")

train_x_df[cat_cols].head()

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,COMPUTERS,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
1,COMPUTER PERIPHERALS ACCESSORIES,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
2,TELEVISIONS HOME CINEMA,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
3,COMPUTERS,COMPUTER PERIPHERALS ACCESSORIES,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
4,TELEVISIONS HOME CINEMA,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE

### Create vocabulary for each type of category (string to number mapping)

In [110]:
def create_shared_vocab(train_df, test_df, cols):

    all_values = pd.concat([
        train_df[col]
        for col in cols
    ] + [
        test_df[col]
        for col in cols
    ]).astype(str)

    unique_values = sorted(
        set(all_values) - {"NONE"}
    )

    vocab = {
        value: idx + 1
        for idx, value in enumerate(unique_values)
    }

    vocab["NONE"] = 0

    return vocab

item_vocab = create_shared_vocab(
    train_x_df,
    test_x_df,
    item_cols
)

make_vocab = create_shared_vocab(
    train_x_df,
    test_x_df,
    make_cols
)

goods_vocab = create_shared_vocab(
    train_x_df,
    test_x_df,
    goods_cols
)

print(item_vocab)

{'2HP ELITEBOOK 850V6': 1, '2LOGITECH PEBBLE M350 BLUETOOTH MOUSE': 2, '2MICROSOFT OFFICE HOME AND STUDENT 2019,': 3, '2TARGUS GEOLITE ESSENTIAL CASE': 4, '2TOSHIBA PORTABLE HARD DRIVE': 5, '6  SPACE GREY 32GB': 6, 'AERIALS REMOTE CONTROLS': 7, 'APPLE PRODUCTDESCRIPTION': 8, 'APPLE S': 9, 'AUDIO ACCESSORIES': 10, 'BABY & CHILD TRAVEL': 11, 'BABY CHANGING': 12, 'BABY CHILD TRAVEL': 13, 'BABY FEEDING': 14, 'BABY PLAY EQUIPMENT': 15, 'BABYWEAR': 16, 'BAGS & CARRY CASES': 17, 'BAGS CARRY CASES': 18, 'BAGS WALLETS ACCESSORIES': 19, 'BAGS, WALLETS & ACCESSORIES': 20, 'BARBECUES & ACCESSORIES': 21, 'BARBECUES ACCESSORIES': 22, 'BARWARE': 23, 'BATH & BODYCARE': 24, 'BATH BODYCARE': 25, 'BATH LINEN': 26, 'BATHROOM': 27, 'BATHROOM ACCESSORIES': 28, 'BATHROOM FIXTURES': 29, 'BED LINEN': 30, 'BEDROOM FURNITURE': 31, 'BLANK MEDIA & MEDIA STORAGE': 32, 'BLANK MEDIA MEDIA STORAGE': 33, 'BOOKS': 34, 'BOYSWEAR': 35, 'CABLES & ADAPTERS': 36, 'CABLES ADAPTERS': 37, 'CARPETS RUGS FLOORING': 38, 'CARPETS, RUGS & FLOORING': 39, 'CHILDREN S ACCESSORIES': 40, 'CHILDREN S FOOTWEAR': 41, 'CHILDREN S FURNITURE': 42, 'CHILDRENS FOOTWEAR': 43, 'CHRISTMAS DECORATIONS': 44, 'COMPUTER NETWORKING': 45, 'COMPUTER PERIPHERALS & ACCESSORIES': 46, 'COMPUTER PERIPHERALS ACCESSORIES': 47, 'COMPUTER SOFTWARE': 48, 'COMPUTERS': 49, 'COOKING APPLIANCES': 50, 'COOKWARE': 51, 'CRAFT': 52, 'DECORATING': 53, 'DECORATIVE ACCESSORIES': 54, 'DIARIES & ORGANISERS': 55, 'DIARIES ORGANISERS': 56, 'DISPOSABLE TABLEWARE CUTLERY': 57, 'DOOR FURNITURE': 58, 'DRESSMAKING': 59, 'EASTER DECORATIONS': 60, 'FACIAL SKINCARE': 61, 'FILING & DESK ACCESSORIES': 62, 'FILING DESK ACCESSORIES': 63, 'FITTED KITCHENS': 64, 'FOOD PREPARATION': 65, 'FOOD STORAGE': 66, 'FRAGRANCE': 67, 'FULFILMENT CHARGE': 68, 'GAMES': 69, 'GAMING': 70, 'GARDENING EQUIPMENT': 71, 'GIFT FOOD DRINK': 72, 'GIFT WRAP': 73, 'GIRLSWEAR': 74, 'GREETING CARDS & PERSONALISED STATIONERY': 75, 'GREETING CARDS PERSONALISED STATIONERY': 76, 'GYM EQUIPMENT': 77, 'HAIRCARE': 78, 'HEALTH & BEAUTY ELECTRICAL': 79, 'HEALTH BEAUTY ACCESSORIES': 80, 'HEALTH BEAUTY ELECTRICAL': 81, 'HEATING & COOLING APPLIANCES': 82, 'HEATING COOLING APPLIANCES': 83, 'HI-FI': 84, 'HOME AND PERSONAL SECURITY': 85, 'HOME OFFICE': 86, 'HOME SAFETY EQUIPMENT': 87, 'HOT DRINK PREPARATION': 88, 'HOUSEHOLD CLEANING': 89, 'HP ELITEBOOK 850V6': 90, 'IMAGING ACCESSORIES': 91, 'IMAGING EQUIPMENT': 92, 'JEWELLERY & WATCHES': 93, 'JEWELLERY WATCHES': 94, 'KITCHEN ACCESSORIES': 95, 'KITCHEN SCALES & MEASURES': 96, 'KITCHEN SCALES MEASURES': 97, 'KITCHEN STORAGE': 98, 'KITCHEN UTENSILS & GADGETS': 99, 'KITCHEN UTENSILS GADGETS': 100, 'LAUNDRY & CLOTHESCARE': 101, 'LAUNDRY APPLIANCES': 102, 'LAUNDRY CLOTHESCARE': 103, 'LIGHTING': 104, 'LINGERIE & HOISERY': 105, 'LINGERIE HOISERY': 106, 'LIVING & DINING FURNITURE': 107, 'LIVING DINING FURNITURE': 108, 'LOGITECH PEBBLE M350 BLUETOOTH MOUSE': 109, 'LUGGAGE': 110, 'MAKEUP': 111, 'MEN S ACCESSORIES': 112, 'MEN S CLOTHES': 113, 'MEN S FOOTWEAR': 114, 'MEN S NIGHTWEAR': 115, 'MEN S SPORTSWEAR': 116, 'MEN S UNDERWEAR SOCKS': 117, 'MENS CLOTHES': 118, 'MENS NIGHTWEAR': 119, 'MENS UNDERWEAR & SOCKS': 120, 'MICROSOFT OFFICE HOME AND STUDENT 2019,': 121, 'NURSERY ACCESSORIES': 122, 'NURSERY EQUIPMENT FURNITURE': 123, 'NURSERY FURNITURE': 124, 'NURSERY LINEN': 125, 'NURSERY TOYS': 126, 'OUTDOOR ACCESSORIES': 127, 'OUTDOOR FURNITURE': 128, 'PAPER & NOTEBOOKS': 129, 'PAPER NOTEBOOKS': 130, 'PARTY DECORATIONS': 131, 'PENS PENCILS': 132, 'PICNICWARE': 133, 'PORTABLE AUDIO EQUIPMENT': 134, 'POWER & BATTERIES': 135, 'POWER BATTERIES': 136, 'PRESERVING & BAKING EQUIPMENT': 137, 'PRESERVING BAKING EQUIPMENT': 138, 'PRINTERS & SCANNERS': 139, 'PRINTERS SCANNERS': 140, 'PRODUCT': 141, 'SCHOOLWEAR': 142, 'SERVICE': 143, 'SOFT FURNISHINGS': 144, 'SPORTS EQUIPMENT': 145, 'STANDS & BRACKETS': 146, 'STANDS BRACKETS': 147, 'STATIONERY SUNDRIES': 148, 'STORAGE & ORGANISATION': 149, 'STORAGE ORGANISATION': 150, 'SUNCARE': 151, 'SUNGLASSES & READING GLASSES': 152, 'SUNGLASSES READING GLASSES': 153, 'TABLE LINEN': 154, 'TABLEWARE': 155, 'TARGUS GEOLITE ESSENTIAL CASE': 156, 'TECHNOLOGY ACCESSORIES': 157, 'TELEPHONE ACCESSORIES': 158, 'TELEPHONES FAX MACHINES TWO-WAY RADIOS': 159, 'TELEPHONES, FAX MACHINES & TWO-WAY RADIOS': 160, 'TELEVISIONS & HOME CINEMA': 161, 'TELEVISIONS HOME CINEMA': 162, 'THEMED GIFTS': 163, 'TOSHIBA PORTABLE HARD DRIVE': 164, 'TOYS': 165, 'UNKNOWN': 166, 'VIDEOS DVD DIGITAL EQUIPMENT': 167, 'WARRANTY': 168, 'WINDOW DRESSING': 169, 'WOMEN S ACCESSORIES': 170, 'WOMEN S CLOTHES': 171, 'WOMEN S FOOTWEAR': 172, 'WOMEN S NIGHTWEAR': 173, 'WOMENS ACCESSORIES': 174, 'WOMENS CLOTHES': 175, 'WOMENS FOOTWEAR': 176, 'WOMENS NIGHTWEAR': 177, 'NONE': 0}

### Encode all categorical columns using the vocabs

In [111]:
def encode_columns(df, cols, vocab):

    for col in cols:

        df[col] = (
            df[col]
            .astype(str)
            .map(vocab)
            .fillna(0)
            .astype(int)
        )

encode_columns(train_x_df,item_cols,item_vocab)
encode_columns(test_x_df,item_cols,item_vocab)
encode_columns(train_x_df,make_cols,make_vocab)
encode_columns(test_x_df,make_cols,make_vocab)
encode_columns(train_x_df,goods_cols,goods_vocab)
encode_columns(test_x_df,goods_cols,goods_vocab)

train_x_df[cat_cols].head()

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,49,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,162,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,49,47,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,162,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [112]:
embedding_sizes = {
    "item": len(item_vocab),
    "make": len(make_vocab),
    "goods": len(goods_vocab)
}

print(embedding_sizes)

{'item': 178, 'make': 888, 'goods': 17029}

### Identify and clean numeric columns (replace NaN with 0)

In [113]:
# Identify numeric columns
numeric_cols = [
    col for col in train_x_df.columns
    if col not in cat_cols + ['ID'] + ['Nb_of_items'] + ['model' + str(i) for i in range(1, 25)]
]

print(numeric_cols)

train_x_df[numeric_cols].head()

['cash_price1', 'cash_price2', 'cash_price3', 'cash_price4', 'cash_price5', 'cash_price6', 'cash_price7', 'cash_price8', 'cash_price9', 'cash_price10', 'cash_price11', 'cash_price12', 'cash_price13', 'cash_price14', 'cash_price15', 'cash_price16', 'cash_price17', 'cash_price18', 'cash_price19', 'cash_price20', 'cash_price21', 'cash_price22', 'cash_price23', 'cash_price24', 'Nbr_of_prod_purchas1', 'Nbr_of_prod_purchas2', 'Nbr_of_prod_purchas3', 'Nbr_of_prod_purchas4', 'Nbr_of_prod_purchas5', 'Nbr_of_prod_purchas6', 'Nbr_of_prod_purchas7', 'Nbr_of_prod_purchas8', 'Nbr_of_prod_purchas9', 'Nbr_of_prod_purchas10', 'Nbr_of_prod_purchas11', 'Nbr_of_prod_purchas12', 'Nbr_of_prod_purchas13', 'Nbr_of_prod_purchas14', 'Nbr_of_prod_purchas15', 'Nbr_of_prod_purchas16', 'Nbr_of_prod_purchas17', 'Nbr_of_prod_purchas18', 'Nbr_of_prod_purchas19', 'Nbr_of_prod_purchas20', 'Nbr_of_prod_purchas21', 'Nbr_of_prod_purchas22', 'Nbr_of_prod_purchas23', 'Nbr_of_prod_purchas24']

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas15,Nbr_of_prod_purchas16,Nbr_of_prod_purchas17,Nbr_of_prod_purchas18,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24
0,889.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,409.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1399.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,689.0,119.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1199.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
# Clean numberic columns by converting to numeric and filling NaNs with 0
train_x_df[numeric_cols] = train_x_df[numeric_cols].apply(pd.to_numeric, errors="coerce").fillna(0)
test_x_df[numeric_cols] = test_x_df[numeric_cols].apply(pd.to_numeric, errors="coerce").fillna(0)

train_x_df[numeric_cols].head()

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas15,Nbr_of_prod_purchas16,Nbr_of_prod_purchas17,Nbr_of_prod_purchas18,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24
0,889.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,409.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1399.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,689.0,119.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1199.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Add aggregated numeric values (like average item price)

In [115]:
qty_cols = [f'Nbr_of_prod_purchas{i}' for i in range(1, 25)]

price_cols = [f'cash_price{i}' for i in range(1, 25)]

train_x_df['total_item_count'] = train_x_df[qty_cols].sum(axis=1)
train_x_df['total_price'] = train_x_df[price_cols].sum(axis=1)
train_x_df['max_price'] = train_x_df[price_cols].max(axis=1)
train_x_df['mean_price'] = train_x_df[price_cols].sum(axis=1) / train_x_df['total_item_count']

test_x_df['total_item_count'] = test_x_df[qty_cols].sum(axis=1)
test_x_df['total_price'] = test_x_df[price_cols].sum(axis=1)
test_x_df['max_price'] = test_x_df[price_cols].max(axis=1)
test_x_df['mean_price'] = test_x_df[price_cols].sum(axis=1) / test_x_df['total_item_count']

# Refresh numeric cols list to include new features
numeric_cols = [
    col for col in train_x_df.columns
    if col not in cat_cols + ['ID'] + ['Nb_of_items'] + ['model' + str(i) for i in range(1, 25)]
]

print(numeric_cols)

train_x_df[numeric_cols].head()

['cash_price1', 'cash_price2', 'cash_price3', 'cash_price4', 'cash_price5', 'cash_price6', 'cash_price7', 'cash_price8', 'cash_price9', 'cash_price10', 'cash_price11', 'cash_price12', 'cash_price13', 'cash_price14', 'cash_price15', 'cash_price16', 'cash_price17', 'cash_price18', 'cash_price19', 'cash_price20', 'cash_price21', 'cash_price22', 'cash_price23', 'cash_price24', 'Nbr_of_prod_purchas1', 'Nbr_of_prod_purchas2', 'Nbr_of_prod_purchas3', 'Nbr_of_prod_purchas4', 'Nbr_of_prod_purchas5', 'Nbr_of_prod_purchas6', 'Nbr_of_prod_purchas7', 'Nbr_of_prod_purchas8', 'Nbr_of_prod_purchas9', 'Nbr_of_prod_purchas10', 'Nbr_of_prod_purchas11', 'Nbr_of_prod_purchas12', 'Nbr_of_prod_purchas13', 'Nbr_of_prod_purchas14', 'Nbr_of_prod_purchas15', 'Nbr_of_prod_purchas16', 'Nbr_of_prod_purchas17', 'Nbr_of_prod_purchas18', 'Nbr_of_prod_purchas19', 'Nbr_of_prod_purchas20', 'Nbr_of_prod_purchas21', 'Nbr_of_prod_purchas22', 'Nbr_of_prod_purchas23', 'Nbr_of_prod_purchas24', 'total_item_count', 'total_price', 'max_price', 'mean_price']

C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3222992749.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['total_item_count'] = train_x_df[qty_cols].sum(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3222992749.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['total_price'] = train_x_df[price_cols].sum(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3222992749.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['max_price'] = train_x_df[price_cols].max(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3222992749.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['mean_price'] = train_x_df[price_cols].sum(axis=1) / train_x_df['total_item_count']
C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3222992749.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['total_item_count'] = test_x_df[qty_cols].sum(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3222992749.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['total_price'] = test_x_df[price_cols].sum(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3222992749.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['max_price'] = test_x_df[price_cols].max(axis=1)
C:\Users\alexn\AppData\Local\Temp\ipykernel_16268\3222992749.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['mean_price'] = test_x_df[price_cols].sum(axis=1) / test_x_df['total_item_count']

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24,total_item_count,total_price,max_price,mean_price
0,889.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,889.0,889.0,889.0
1,409.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,409.0,409.0,409.0
2,1399.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1399.0,1399.0,1399.0
3,689.0,119.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,808.0,689.0,404.0
4,1199.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1199.0,1199.0,1199.0

### Scaling / Normalisation

In [116]:
for col in numeric_cols:

    train_x_df[col] = np.log1p(train_x_df[col])
    test_x_df[col] = np.log1p(test_x_df[col])

train_x_df[numeric_cols].head()

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24,total_item_count,total_price,max_price,mean_price
0,6.791221,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,6.791221,6.791221,6.791221
1,6.016157,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,6.016157,6.016157,6.016157
2,7.244228,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,7.244228,7.244228,7.244228
3,6.536692,4.787492,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.098612,6.695799,6.536692,6.003887
4,7.090077,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,7.090077,7.090077,7.090077

### Convert to Tensors

In [117]:
import torch

X_cat = torch.tensor(
    train_x_df[cat_cols].values,
    dtype=torch.long
)

X_cat_test = torch.tensor(
    test_x_df[cat_cols].values,
    dtype=torch.long
)

X_num = torch.tensor(
    train_x_df[numeric_cols].values,
    dtype=torch.float32
)

X_num_test = torch.tensor(
    test_x_df[numeric_cols].values,
    dtype=torch.float32
)

y = train_y_df["fraud_flag"].values

y_tensor = torch.tensor(
    y,
    dtype=torch.float32
)

print(X_cat.shape)
print(X_num.shape)
print(y_tensor.shape)

print(X_cat[:1])
print(X_num[:1])

torch.Size([92790, 72])
torch.Size([92790, 52])
torch.Size([92790])
tensor([[   49,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,    34,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0, 12760,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]])
tensor([[6.7912, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6931, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.6931, 6.7912, 6.7912, 6.7912]])

### Train / Validation Split

In [118]:
from sklearn.model_selection import train_test_split

X_cat_train, X_cat_val, X_num_train, X_num_val, y_train, y_val = train_test_split(
    X_cat, X_num, y_tensor, test_size=0.15, random_state=42
)

print(type(y_val))
print(np.shape(y_val))
print(y_val[:95])

<class 'torch.Tensor'>
torch.Size([13919])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1.])

### Create Dataset class

In [119]:
from torch.utils.data import Dataset

class FraudDataset(Dataset):

    def __init__(self, X_cat, X_num, y=None):

        self.X_cat = X_cat
        self.X_num = X_num
        self.y = y

    def __len__(self):
        return len(self.X_cat)

    def __getitem__(self, idx):

        if self.y is not None:
            return (
                self.X_cat[idx],
                self.X_num[idx],
                self.y[idx]
            )

        return (
            self.X_cat[idx],
            self.X_num[idx]
        )

### Undersampling fraud-like samples in the non-fraud data

In [120]:
import numpy as np

undersample_factor = 5

y_train_np = y_train.numpy()

fraud_idx = np.where(y_train_np == 1)[0]
normal_idx = np.where(y_train_np == 0)[0]

print("Before:")
print("Frauds :", len(fraud_idx))
print("Non-Fraud:", len(normal_idx))
print("Train size:", len(y_train))

# Compute top-5 fraud item values across item1..item24
fraud_item_vals = X_cat_train[fraud_idx, :24].numpy().flatten()
fraud_item_vals = fraud_item_vals[fraud_item_vals != 0]

unique, counts = np.unique(fraud_item_vals, return_counts=True)
top5_fraud_items = unique[np.argsort(counts)[::-1][:5]]

print("Top 5 fraud item values:", top5_fraud_items)

# Find non-fraud rows that contain any of those top-5 fraud item values
normal_item_vals = X_cat_train[normal_idx, :24].numpy()
normal_top5_mask = np.isin(normal_item_vals, top5_fraud_items).any(axis=1)

normal_top5_idx = normal_idx[normal_top5_mask]
normal_other_idx = normal_idx[~normal_top5_mask]

# Undersample only the non-fraud rows with top-5 fraud item values
n_top5_to_keep = min(
    int(len(normal_top5_idx) / undersample_factor),
    len(normal_top5_idx)
)

np.random.seed(42)
selected_top5_idx = np.random.choice(
    normal_top5_idx,
    size=n_top5_to_keep,
    replace=False
)

selected_idx = np.concatenate([
    fraud_idx,
    normal_other_idx,
    selected_top5_idx
])

np.random.shuffle(selected_idx)

X_cat_train = X_cat_train[selected_idx]
X_num_train = X_num_train[selected_idx]
y_train = y_train[selected_idx]

print("After:")
print("Frauds :", int(y_train.sum()))
print("Non-Fraud:", len(y_train) - int(y_train.sum()))
print("Train size:", len(y_train))
print("Kept non-fraud with top-5 fraud items:", len(selected_top5_idx))
print("Kept non-fraud without top-5 fraud items:", len(normal_other_idx))

Before:
Frauds : 1107
Non-Fraud: 77764
Train size: 78871
Top 5 fraud item values: [ 49  68 160  10  47]
After:
Frauds : 1107
Non-Fraud: 31096
Train size: 32203
Kept non-fraud with top-5 fraud items: 11666
Kept non-fraud without top-5 fraud items: 19430

### Create the Datasets and Dataloaders

In [121]:
train_dataset = FraudDataset(
    X_cat_train,
    X_num_train,
    y_train
)

val_dataset = FraudDataset(
    X_cat_val,
    X_num_val,
    y_val
)

test_dataset = FraudDataset(
    X_cat_test,
    X_num_test
)

In [122]:
from torch.utils.data import DataLoader

batch_size = 512

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)

### Define Embedding Layers and main Neural Network

In [123]:
import torch
import torch.nn as nn

class FraudModel(nn.Module):

    def __init__(self, embedding_sizes, n_numeric):

        super().__init__()

        # Embedding dimensions
        item_dim = 8
        make_dim = 16
        goods_dim = 64

        # Shared embedding tables
        self.item_embedding = nn.Embedding(
            embedding_sizes["item"],
            item_dim,
            padding_idx=0
        )
        self.make_embedding = nn.Embedding(
            embedding_sizes["make"],
            make_dim,
            padding_idx=0
        )
        self.goods_embedding = nn.Embedding(
            embedding_sizes["goods"],
            goods_dim,
            padding_idx=0
        )

        total_embedding_dim = (
            item_dim +
            make_dim +
            goods_dim
        )

        # Main classifier
        self.fc = nn.Sequential(

            nn.Linear(
                total_embedding_dim + n_numeric,
                64
            ),

            nn.ReLU(),

            nn.Dropout(0.25),

            nn.Linear(64, 32),

            nn.ReLU(),

            nn.Dropout(0.2),

            nn.Linear(32, 1)
        )

    # Apply masked mean pooling to filter out padded (empty) embeddings to maximize the importance/influence of actual values
    def masked_mean_pooling(
        self,
        embeddings,
        x
    ):

        # Mask real tokens
        mask = (x != 0).float()

        # Expand mask for embedding dimension
        mask = mask.unsqueeze(-1)

        # Zero-out padded embeddings
        masked_embeddings = embeddings * mask

        # Sum embeddings
        summed = masked_embeddings.sum(dim=1)

        # Count non-padded entries
        counts = mask.sum(dim=1)
        counts = counts.clamp(min=1)

        # Mean pooling
        pooled = summed / counts

        return pooled

    def forward(self, x_cat, x_num):

        # Split categorical groups
        item_x = x_cat[:, 0:24]
        make_x = x_cat[:, 24:48]
        goods_x = x_cat[:, 48:72]

        # Embeddings
        item_emb = self.item_embedding(item_x)
        make_emb = self.make_embedding(make_x)
        goods_emb = self.goods_embedding(goods_x)

        # Masked mean pooling
        item_pooled = self.masked_mean_pooling(
            item_emb,
            item_x
        )
        make_pooled = self.masked_mean_pooling(
            make_emb,
            make_x
        )
        goods_pooled = self.masked_mean_pooling(
            goods_emb,
            goods_x
        )

        # Concatenate pooled embeddings
        x = torch.cat([
            item_pooled,
            make_pooled,
            goods_pooled,
            x_num
        ], dim=1)

        # MLP
        x = self.fc(x)

        return x.squeeze()

### Instantiate Model

In [124]:
model = FraudModel(
    embedding_sizes=embedding_sizes,
    n_numeric=len(numeric_cols)
)

### Prepare for Training and Validation

In [125]:
criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [126]:
print(np.unique(y)[:200])
print(y.shape)

[0 1]
(92790,)

### Train and Validate

In [127]:
from sklearn.metrics import average_precision_score

best_score = 0

for epoch in range(100):

    # TRAINING
    model.train()

    train_losses = []

    for X_cat_batch, X_num_batch, y_batch in train_loader:

        optimizer.zero_grad()

        logits = model(X_cat_batch, X_num_batch)

        loss = criterion(logits, y_batch)

        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            1.0
        )

        optimizer.step()

        train_losses.append(loss.item())

    # VALIDATION
    model.eval()

    all_probs = []
    all_targets = []

    with torch.no_grad():

        for X_cat_batch, X_num_batch, y_batch in val_loader:

            logits = model(X_cat_batch, X_num_batch)

            probs = torch.sigmoid(logits)

            all_probs.extend(probs.cpu().numpy())

            all_targets.extend(y_batch.cpu().numpy())

    # Calculate PR-AUC
    pr_auc = average_precision_score(
        all_targets,
        all_probs
    )

    # Save best model based on PR-AUC
    if pr_auc > best_score:
        best_score = pr_auc
        torch.save(
            model.state_dict(),
            "best_model.pt"
        )
        print(f"New best model saved with PR-AUC: {pr_auc:.4f}")

    print(
        f"Epoch {epoch} | "
        f"Loss {np.mean(train_losses):.4f} | "
        f"PR-AUC {pr_auc:.4f}"
    )

# Restore best model
model.load_state_dict(torch.load("best_model.pt"))

New best model saved with PR-AUC: 0.0264
Epoch 0 | Loss 0.2148 | PR-AUC 0.0264
New best model saved with PR-AUC: 0.0377
Epoch 1 | Loss 0.1238 | PR-AUC 0.0377
New best model saved with PR-AUC: 0.0468
Epoch 2 | Loss 0.1157 | PR-AUC 0.0468
New best model saved with PR-AUC: 0.0635
Epoch 3 | Loss 0.1091 | PR-AUC 0.0635
New best model saved with PR-AUC: 0.0743
Epoch 4 | Loss 0.1064 | PR-AUC 0.0743
New best model saved with PR-AUC: 0.0873
Epoch 5 | Loss 0.1033 | PR-AUC 0.0873
New best model saved with PR-AUC: 0.0923
Epoch 6 | Loss 0.1002 | PR-AUC 0.0923
New best model saved with PR-AUC: 0.1031
Epoch 7 | Loss 0.0992 | PR-AUC 0.1031
New best model saved with PR-AUC: 0.1069
Epoch 8 | Loss 0.0970 | PR-AUC 0.1069
New best model saved with PR-AUC: 0.1150
Epoch 9 | Loss 0.0958 | PR-AUC 0.1150
New best model saved with PR-AUC: 0.1188
Epoch 10 | Loss 0.0945 | PR-AUC 0.1188
Epoch 11 | Loss 0.0926 | PR-AUC 0.1155
Epoch 12 | Loss 0.0909 | PR-AUC 0.1110
New best model saved with PR-AUC: 0.1223
Epoch 13 | Loss 0.0896 | PR-AUC 0.1223
Epoch 14 | Loss 0.0895 | PR-AUC 0.1219
New best model saved with PR-AUC: 0.1262
Epoch 15 | Loss 0.0871 | PR-AUC 0.1262
New best model saved with PR-AUC: 0.1347
Epoch 16 | Loss 0.0862 | PR-AUC 0.1347
New best model saved with PR-AUC: 0.1367
Epoch 17 | Loss 0.0863 | PR-AUC 0.1367
Epoch 18 | Loss 0.0860 | PR-AUC 0.1334
Epoch 19 | Loss 0.0842 | PR-AUC 0.1316
New best model saved with PR-AUC: 0.1410
Epoch 20 | Loss 0.0840 | PR-AUC 0.1410
Epoch 21 | Loss 0.0835 | PR-AUC 0.1355
Epoch 22 | Loss 0.0832 | PR-AUC 0.1392
Epoch 23 | Loss 0.0829 | PR-AUC 0.1380
New best model saved with PR-AUC: 0.1441
Epoch 24 | Loss 0.0823 | PR-AUC 0.1441
Epoch 25 | Loss 0.0819 | PR-AUC 0.1290
Epoch 26 | Loss 0.0812 | PR-AUC 0.1378
Epoch 27 | Loss 0.0809 | PR-AUC 0.1400
Epoch 28 | Loss 0.0804 | PR-AUC 0.1376
Epoch 29 | Loss 0.0807 | PR-AUC 0.1316
Epoch 30 | Loss 0.0812 | PR-AUC 0.1345
Epoch 31 | Loss 0.0806 | PR-AUC 0.1430
Epoch 32 | Loss 0.0812 | PR-AUC 0.1315
Epoch 33 | Loss 0.0796 | PR-AUC 0.1372
Epoch 34 | Loss 0.0798 | PR-AUC 0.1305
Epoch 35 | Loss 0.0798 | PR-AUC 0.1348
Epoch 36 | Loss 0.0790 | PR-AUC 0.1368
Epoch 37 | Loss 0.0788 | PR-AUC 0.1359
Epoch 38 | Loss 0.0781 | PR-AUC 0.1397
Epoch 39 | Loss 0.0787 | PR-AUC 0.1405
Epoch 40 | Loss 0.0789 | PR-AUC 0.1309
Epoch 41 | Loss 0.0781 | PR-AUC 0.1358
Epoch 42 | Loss 0.0781 | PR-AUC 0.1343
Epoch 43 | Loss 0.0783 | PR-AUC 0.1370
Epoch 44 | Loss 0.0780 | PR-AUC 0.1349
Epoch 45 | Loss 0.0780 | PR-AUC 0.1336
Epoch 46 | Loss 0.0775 | PR-AUC 0.1363
Epoch 47 | Loss 0.0781 | PR-AUC 0.1292
Epoch 48 | Loss 0.0773 | PR-AUC 0.1311
Epoch 49 | Loss 0.0774 | PR-AUC 0.1351
Epoch 50 | Loss 0.0767 | PR-AUC 0.1418
Epoch 51 | Loss 0.0773 | PR-AUC 0.1372
Epoch 52 | Loss 0.0773 | PR-AUC 0.1383
Epoch 53 | Loss 0.0763 | PR-AUC 0.1407
Epoch 54 | Loss 0.0767 | PR-AUC 0.1306
Epoch 55 | Loss 0.0764 | PR-AUC 0.1332
Epoch 56 | Loss 0.0769 | PR-AUC 0.1200
Epoch 57 | Loss 0.0754 | PR-AUC 0.1302
Epoch 58 | Loss 0.0767 | PR-AUC 0.1199
Epoch 59 | Loss 0.0759 | PR-AUC 0.1316
Epoch 60 | Loss 0.0758 | PR-AUC 0.1339
Epoch 61 | Loss 0.0769 | PR-AUC 0.1317
Epoch 62 | Loss 0.0753 | PR-AUC 0.1310
Epoch 63 | Loss 0.0745 | PR-AUC 0.1247
Epoch 64 | Loss 0.0754 | PR-AUC 0.1344
Epoch 65 | Loss 0.0760 | PR-AUC 0.1295
Epoch 66 | Loss 0.0749 | PR-AUC 0.1284
Epoch 67 | Loss 0.0748 | PR-AUC 0.1249
Epoch 68 | Loss 0.0757 | PR-AUC 0.1152
Epoch 69 | Loss 0.0752 | PR-AUC 0.1212
Epoch 70 | Loss 0.0750 | PR-AUC 0.1261
Epoch 71 | Loss 0.0747 | PR-AUC 0.1299
Epoch 72 | Loss 0.0749 | PR-AUC 0.1264
Epoch 73 | Loss 0.0742 | PR-AUC 0.1374
Epoch 74 | Loss 0.0753 | PR-AUC 0.1301
Epoch 75 | Loss 0.0738 | PR-AUC 0.1319
Epoch 76 | Loss 0.0741 | PR-AUC 0.1287
Epoch 77 | Loss 0.0751 | PR-AUC 0.1316
Epoch 78 | Loss 0.0747 | PR-AUC 0.1311
Epoch 79 | Loss 0.0735 | PR-AUC 0.1287
Epoch 80 | Loss 0.0735 | PR-AUC 0.1347
Epoch 81 | Loss 0.0743 | PR-AUC 0.1268
Epoch 82 | Loss 0.0744 | PR-AUC 0.1311
Epoch 83 | Loss 0.0735 | PR-AUC 0.1218
Epoch 84 | Loss 0.0745 | PR-AUC 0.1273
Epoch 85 | Loss 0.0735 | PR-AUC 0.1297
Epoch 86 | Loss 0.0743 | PR-AUC 0.1262
Epoch 87 | Loss 0.0733 | PR-AUC 0.1217
Epoch 88 | Loss 0.0736 | PR-AUC 0.1263
Epoch 89 | Loss 0.0737 | PR-AUC 0.1278
Epoch 90 | Loss 0.0727 | PR-AUC 0.1232
Epoch 91 | Loss 0.0733 | PR-AUC 0.1217
Epoch 92 | Loss 0.0732 | PR-AUC 0.1305
Epoch 93 | Loss 0.0732 | PR-AUC 0.1294
Epoch 94 | Loss 0.0735 | PR-AUC 0.1270
Epoch 95 | Loss 0.0733 | PR-AUC 0.1240
Epoch 96 | Loss 0.0731 | PR-AUC 0.1321
Epoch 97 | Loss 0.0730 | PR-AUC 0.1219
Epoch 98 | Loss 0.0734 | PR-AUC 0.1317
Epoch 99 | Loss 0.0726 | PR-AUC 0.1280

### Test Set Predicitons

In [128]:
model.eval()

test_probs = []

with torch.no_grad():

    for X_cat_batch, X_num_batch in test_loader:

        logits = model(X_cat_batch, X_num_batch)

        probs = torch.sigmoid(logits)

        test_probs.extend(probs.cpu().numpy().flatten())

### Write submission CSV for challenge

In [129]:
submission = pd.DataFrame({
    "index": range(len(test_x_df)),
    "ID": test_x_df["ID"],
    "fraud_flag": test_probs
})

submission.to_csv("submission.csv", index=False)

print(submission.head())
print("\nsubmission.csv saved!")

   index     ID    fraud_flag
0      0  64707  2.158671e-08
1      1  63919  1.065214e-06
2      2  15664  2.188889e-02
3      3   6626  7.200053e-02
4      4  26766  9.202587e-02

submission.csv saved!